//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySwatter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugUsers
    {
        public BugUsers()
        {
            this.ProjectUsers = new HashSet<ProjectUsers>();
            this.TicketAttachments = new HashSet<TicketAttachments>();
            this.TicketComments = new HashSet<TicketComments>();
            this.TicketHistories = new HashSet<TicketHistories>();
            this.TicketNotifications = new HashSet<TicketNotifications>();
            this.Tickets = new HashSet<Tickets>();
            this.Tickets1 = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string userName { get; set; }
    
        public virtual ICollection<ProjectUsers> ProjectUsers { get; set; }
        public virtual ICollection<TicketAttachments> TicketAttachments { get; set; }
        public virtual ICollection<TicketComments> TicketComments { get; set; }
        public virtual ICollection<TicketHistories> TicketHistories { get; set; }
        public virtual ICollection<TicketNotifications> TicketNotifications { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual ICollection<Tickets> Tickets1 { get; set; }
    }
}
