//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySwatter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SwatterEntities : DbContext
    {
        public SwatterEntities()
            : base("name=SwatterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BugUsers> BugUsers { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectUsers> ProjectUsers { get; set; }
        public virtual DbSet<TicketAttachments> TicketAttachments { get; set; }
        public virtual DbSet<TicketComments> TicketComments { get; set; }
        public virtual DbSet<TicketHistories> TicketHistories { get; set; }
        public virtual DbSet<TicketNotifications> TicketNotifications { get; set; }
        public virtual DbSet<TicketPriorities> TicketPriorities { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TicketStatuses> TicketStatuses { get; set; }
        public virtual DbSet<TicketTypes> TicketTypes { get; set; }
    }
}
