//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySwatter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.ProjectUsers = new HashSet<ProjectUsers>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProjectUsers> ProjectUsers { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
